# Generated by Django 5.2 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("barrier", "Barrier option"),
                    ("collar", "Collar Up-and-In"),
                    ("fence", "Fence Up-and-In"),
                    ("nitro", "Nitro Call Up-and-Out"),
                    ("double_up_ko", "Double Up KO"),
                    ("solver", "Zero-cost solver"),
                    ("scenario", "Scenario analysis"),
                ],
                max_length=20,
            ),
        ),
    ]
