# Generated by Django 5.2 on 2026-07-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricing", "0002_calculation_nitro_double_up_ko"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="kind",
            field=models.CharField(
                choices=[
                    ("barrier", "Barrier option"),
                    ("collar", "Collar Up-and-In"),
                    ("fence", "Fence Up-and-In"),
                    ("nitro", "Nitro Call Up-and-Out"),
                    ("double_up_ko", "Double Up KO"),
                    ("box_ko", "Box KO"),
                    ("box_bullet", "Box Bullet"),
                    ("bullet", "Bullet"),
                    ("bullet_plus", "Bullet Plus"),
                    ("golden_bullet", "Golden Bullet"),
                    ("collar_kiko", "Collar KI.KO"),
                    ("fence_kiko", "Fence KI.KO"),
                    ("call_kiko", "Call KI.KO"),
                    ("digital", "Cash digital"),
                    ("solver", "Zero-cost solver"),
                    ("scenario", "Scenario analysis"),
                ],
                max_length=20,
            ),
        ),
    ]
